import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored third-party component (mapcn), kept as published: see docs/adr/0006.
    "components/ui/map.tsx",
    // Generated by scripts/copy-maplibre-worker.mjs.
    "public/maplibre/**",
  ]),
]);

export default eslintConfig;
